coverage:
  status:
    project:
      default:
        # basic
        target: 80%
        threshold: 2%
        base: auto 
 
  ignore:
  - "py-wacz/tests/*"
  - "py-wacz/wacz/__init__.py"
  - "py-wacz/wacz/__main__.py"
